language: objective-c
osx_image: xcode9.0
branches:
  only:
    - master


before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
    
