language: objective-c

branches:
  only:
    - master

podfile: ./Demo/Podfile
osx_image: xcode8.2
cache: cocoapods

script:
  - xcodebuild -workspace ./Example/NView.xcworkspace -scheme NView -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
